### ISSUE TITLE
Alert Error

### ISSUE THREAD

**Issue by EpicStreamMan** [wizard04wsu/epic-overlay#23]
![image](https://cloud.githubusercontent.com/assets/16730270/12371018/bf28f356-bbf3-11e5-8b67-46db0e5e2c37.png)

see if you can fix that error please ;c)

**Comment by EpicStreamMan** [comment]
I was thinking instead of a error message pop up just have a text box or something with an error log in it that we can go back through or clear. cuz it seems when you say ok to the error it fixes it self but while the error message is up script stops of course ;c)

**Comment by wizard04wsu** [comment]
I still don't know what's causing the error, but it's now added to a log instead of showing an alert.
